"""add todo type column

Revision ID: 1272181f4a83
Revises: 25b9e0e0accc
Create Date: 2023-10-29 13:29:25.348135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1272181f4a83'
down_revision: Union[str, None] = '25b9e0e0accc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('todo_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'todo_type')
    # ### end Alembic commands ###
