"""add category column

Revision ID: 721fa8dc11fd
Revises: 
Create Date: 2023-10-29 13:05:18.422623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721fa8dc11fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_column('todos', 'category')
    # ### end Alembic commands ###
